package com.nozama.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class SupprimerclientTest {
  private WebDriver driver;
 // private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void testGoogleSearch() throws InterruptedException {
	//System.setProperty("webdriver.chrome.driver", "C:\\Users\\Administrateur\\Downloads\\chromedriver_win32\\chromedriver.exe");
	System.setProperty("webdriver.gecko.driver", "C:\\Users\\Administrateur\\Downloads\\geckodriver-v0.29.0-win64\\geckodriver.exe");

	
	driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
   // vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void supprimerclient(String[] args) {

    driver.get("http://127.0.0.1/nozama/");
    driver.manage().window().setSize(new Dimension(746, 800));
    
//	String utilisateur = "may";
    
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#edit-name-wrapper > label"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("edit-name")).click();
    driver.findElement(By.id("edit-name")).sendKeys("admin1");
    driver.findElement(By.id("edit-pass")).click();
    driver.findElement(By.id("edit-pass")).sendKeys("admin1");
    {
      List<WebElement> elements = driver.findElements(By.id("edit-submit"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("edit-submit")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Liste des utilisateurs"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Liste des utilisateurs")).click();
    
//------------IF ELSE : si l'utilisateur may est présent -> le supprimer sinon se déconnecter
//    if (utilisateur == "may")
    
    {
      List<WebElement> elements = driver.findElements(By.linkText("may"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("modifier"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("modifier")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("edit-delete"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("edit-delete")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("edit-submit"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("edit-submit")).click();
    /*   {
      List<WebElement> elements = driver.findElements(By.xpath("/html/body/div/div/div[5]/div/div/div[1]/div/div[4]/div/h2"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//*[@id=\\\"block-menu-menu-logout\\\"]/div/div/ul/li/a")).click();
    driver.findElement(By.cssSelector("#edit-name-wrapper > label")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#edit-name-wrapper > label"));
      assert(elements.size() > 0);
    }*/
    {
        List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"block-menu-menu-logout\"]/div/div/ul/li/a"));
        assert(elements.size() > 0);
      }
      driver.findElement(By.xpath("//*[@id=\"block-menu-menu-logout\"]/div/div/ul/li/a")).click();
      {
        List<WebElement> elements = driver.findElements(By.cssSelector("#edit-name-wrapper > label"));
        assert(elements.size() > 0);
      }
  }
}
